/**
 * AgentPack template content
 */

export const README_MD = `# OpenClaw Agent Pack

Generated by OpenClaw Pixel Office.

## Quick Start

1. Extract this zip
2. Copy \`openclaw-agents-to-merge.json\` into your \`openclaw.json\` under the \`agents\` key
3. Run your OpenClaw runtime with this pack as workspace

## Structure

- \`workflow-<id>/\` — IDENTITY.md, SOUL.md per agent
- \`AGENTS.md\` — Team overview and routing hints
- \`openclaw-agents-to-merge.json\` — Agent list to merge into openclaw.json
- \`office/\` — Layout, map, plan templates (when configured)
`;
